apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitandblow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hitandblow
  template:
    metadata:
      labels:
        app: hitandblow
    spec:
      containers:
      - name: hitandblow
        image: dqx0/hitandblow:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hitandblow-service
spec:
  type: LoadBalancer
  selector:
    app: hitandblow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080