// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/games": {
            "post": {
                "description": "新しいゲームを開始し、ゲームIDとメッセージを返す",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "ゲーム開始",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/server.StartNewGameResponse"
                        }
                    }
                }
            }
        },
        "/games/{gameId}/guess": {
            "post": {
                "description": "ゲームに対して推測を送信し、判定結果を返す",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "ゲームの推測",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ゲームID",
                        "name": "gameId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "推測情報",
                        "name": "guess",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.GuessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "推測結果",
                        "schema": {
                            "$ref": "#/definitions/server.GuessResponse"
                        }
                    },
                    "400": {
                        "description": "無効なリクエスト",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "ゲームが見つかりません",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.GuessRequest": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "string"
                }
            }
        },
        "server.GuessResponse": {
            "type": "object",
            "properties": {
                "blow": {
                    "type": "integer"
                },
                "clear": {
                    "type": "boolean"
                },
                "hit": {
                    "type": "integer"
                },
                "tries": {
                    "type": "integer"
                }
            }
        },
        "server.StartNewGameResponse": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hit and Blow API",
	Description:      "Hit and Blow GameのAPIドキュメント",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
