name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: dqx0/hitandblow:v1.0.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gcp-dqx0
          export_default_credentials: true

      - name: Install GKE gcloud auth plugin
        run: gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials hitandblow-cluster --region us-central1 --project gcp-dqx0

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/hitandblow hitandblow=dqx0/hitandblow:v1.0.0
          kubectl rollout status deployment/hitandblow